# Generated by Django 3.2.7 on 2021-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=100)),
                ('website', models.URLField(blank='', help_text='The Publishers website')),
                ('email', models.EmailField(blank='', help_text='The Publishers email', max_length=254)),
            ],
        ),
    ]
